name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: dotnet restore DirectWrite.Avalonia.slnx
      - name: Build
        run: dotnet build DirectWrite.Avalonia.slnx -c Release --no-restore
      - name: Test
        run: dotnet test DirectWrite.Avalonia.slnx -c Release --no-build
      - name: Pack
        run: dotnet pack DirectWrite.Avalonia.slnx -c Release --no-build
